version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8002
    volumes: 
      - './app:/usr/src/app'
    ports:
      - "8002:8002"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment: 
      MYSQL_NAME: django_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
  db:
    image: mysql:5.7
    volumes: 
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: django_development
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
